POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234*"
}

###
GET http://localhost:8080/api/users/current
Authorization: Bearer eyJ1c2VySWQiOjcsImlhdCI6MTc0OTQzNDcyMCwiZXhwIjoxNzQ5NDM4MzIwfQ.P0hfjvwL0trrfqgYrXUqqWwl4vkXpKsOHpbTs0OQm0Q

###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "test1234",
  "confirmPassword": "test1234",
  "firstName": "test",
  "lastName": "1234"
}

###
POST http://localhost:8080/api/7/fields/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NDkzNDI2NjR9.d5WjiFPpNmHNQBf0SPElU50wHHVTJ0gNXa_NxBvgWyQ
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="field"

{
    "type": "Futsal",
    "price": 120000
}

--boundary
Content-Disposition: form-data; name="files"; filename="dummy-image.jpg"
Content-Type: image/jpeg

@/path/to/dummy-image.jpg

--boundary--

###
POST http://localhost:8080/api/users/google

###
POST http://localhost:5000/recommendations
Content-Type: application/json

{
  "user_id": 1,
  "user_lat": -6.208898748739306,
  "user_lon": 106.7742668929873,
  "top_n": 5
}

###
GET http://localhost:8080/api/venues-ai
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NTAzNjgwMzR9.87beqk4J2S0ubzPkDe1U3Vk_mxx7gVCTSLI49RoGuuE