openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: user service API
servers:
  - url: https://api.example.com

security:
  - bearerAuth: []

paths:
  /api/users/register:
    post:
      summary: Register
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '200':
          description: Pengguna berhasil didaftarkan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/users/login:
    post:
      summary: Login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autentikasi berhasil, token diberikan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/users/current:
    get:
      summary: Get current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profil pengguna ditemukan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/users/logout:
    delete:
      summary: Logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: logout successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/users/changeUsername/{id}:
    patch:
      summary: Change Username
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID unik pengguna
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUsername'
      responses:
        '200':
          description: Nama pengguna berhasil diubah
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/users/changePassword/{id}:
    patch:
      summary: Change password
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID unik pengguna
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
      responses:
        '200':
          description: Password berhasil diubah
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      email:
                        type: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/users/forgot-password:
    post:
      summary: Forgot password
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
      responses:
        '200':
          description: Otp send
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500' :
          description: Failed to send OTP email

  /api/users/validate-otp:
    post:
      summary: Validate OTP
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateOtp'
      responses:
        '200':
          description: OTP Is valid
        '403':
          description: Otp Incorrect
        '500' :
          description: Failed to send OTP email

  /api/users/reset-password:
      post:
        summary: Reset Password
        security:
          - bearerAuth: [ ]
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPassword'
        responses:
          '200':
            description: Reset Successfully
          '403':
            description: Otp Incorrect


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token JWT harus dikirim di header Authorization dengan format':' 'Bearer {token}'

  schemas:
    RegisterUser:
      type: object
      required:
        - email
        - password
        - confirmPassword
        - firstName
        - lastName
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        confirmPassword:
          type: string
        firstName:
          type: string
        lastName:
          type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    AuthToken:
      type: object
      properties:
        token:
          type: string
          description: Token JWT untuk autentikasi

    UserResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: integer
            email:
              type: string
              format: email
            firstName:
              type: string
            lastName:
              type: string

    UpdateUsername:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        lastName:
          type: string

    ChangePassword:
      type: object
      required:
        - password
        - confirmPassword
      properties:
        password:
          type: string
        confirmPassword:
          type: string

    ForgotPassword:
      type: object
      required:
        - Email
      properties:
        Email:
          type: string

    ValidateOtp:
      type: object
      required:
        - otp
      properties:
        otp:
          type: string

    ResetPassword:
      type: object
      required:
        - newPassword
        - confirmPassword
        - email
      properties:
        newPassowrd:
          type: string
        confirmPassowrd:
          type: string
        email:
          type: string


  responses:
    BadRequest:
      description: Input tidak valid
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    Unauthorized:
      description: Autentikasi gagal, token tidak valid atau tidak diberikan

    Forbidden:
      description: Akses ditolak, token valid tapi tidak punya hak akses

    NotFound:
      description: Resource tidak ditemukan
